apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: my-nodedbapp
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: nodedb-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        # Run this image
        image: suyashmishra013/emaildb:01
      - name: mongodb
        # Run this image
        image: mongo:latest
        