apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-app
  name: serverapp
spec:
  ports:
  - name: http
    port: 8800
    targetPort: 3500
  selector:
    app: server-app
  type: LoadBalancer
status:
  loadBalancer: {}
